# This file was generated by GoReleaser. DO NOT EDIT.
cask "rpup" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2dc90f436b43c9930bc856c542535eea14102281b94b99f7eed9511e54d30ce6"
      url "https://github.com/code-dogs-dev/rpup/releases/download/v#{version}/rpup_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28eeef9a4d0dbfd859ca1210c1a1b22b583e1b6133781a804ffb3d03ddeef2fe"
      url "https://github.com/code-dogs-dev/rpup/releases/download/v#{version}/rpup_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1495b2c3470daacb529c51cd1ae3931bdf5df8628429d15a11bd5fac3d81b1a8"
      url "https://github.com/code-dogs-dev/rpup/releases/download/v#{version}/rpup_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a7202f3024d6388d683a378050f3591bb77751866302d253c08d6791e9a3b87"
      url "https://github.com/code-dogs-dev/rpup/releases/download/v#{version}/rpup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rpup"
  desc "A fork-free pup — drop-in chruby replacement that switches Ruby without spawning ruby"
  homepage "https://github.com/code-dogs-dev/rpup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rpup"

  # No zap stanza required

  caveats <<~EOS
    rpup switches Ruby by printing shell to eval. Wire up the auto-switch hook
    by adding this to your ~/.zshrc (or ~/.bashrc):

      eval "$(rpup hook zsh)"     # bash: rpup hook bash

    Then `cd` into a project with a .ruby-version and rpup switches for you.
    One-shot switching without the hook: eval "$(rpup use 3.4.5)".
  EOS
end
